config/routes.rb
Rails.application.routes.draw do

  scope :api do
    scope :v1 do
      scope '/enter' do
        post '/' => 'slack_posts#create_entry'
        get '/:id' => 'slack_posts#show'
      end
      scope '/leave' do
        post '/' => 'slack_posts#create_exit'
        get '/:id' => 'slack_posts#show'
      end
      scope '/uuids' do
        get '/' => 'uuids#index'
      end
    end
  end
  scope :admin do
    devise_for :users
    scope '/' do
      get '/' => 'admin#index'
      resources :uuids
    end
    resources :slack_integrations
  end

end

app/models/slack_integration.rb
class SlackIntegration < ActiveRecord::Base
end

app/models/slack_post.rb
# == Schema Information
#
# Table name: slack_posts
#
#  id         :integer          not null, primary key
#  name       :string
#  location   :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class SlackPost < ActiveRecord::Base
	validates :name, presence: true
	validates :location, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/uuid.rb
class Uuid < ActiveRecord::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate_user!

  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  respond_to :json, :html
end

app/controllers/slack_integrations_controller.rb
class SlackIntegrationsController < ApplicationController
  before_action :set_integration, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  def index
    if current_user.admin?
      @slack_integrations = SlackIntegration.all
    else
      render_404
    end
  end

  def show
    render_404 unless current_user.admin?
  end

  def new
    if current_user.admin?
      @slack_integration = SlackIntegration.new
    else
      render_404
    end
  end

  def edit
    render_404 unless current_user.admin?
  end

  def create
    if current_user.admin?
      @slack_integration = SlackIntegration.new(slack_integration_params)

      if @slack_integration.save
        redirect_to @slack_integration, notice: 'Integration was successfully created.'
      else
        render :new
      end

    else 
      render_404
    end
  end

  def update
    if current_user.admin?
      if @slack_integration.update(slack_integration_params)
        redirect_to @slack_integration, notice: 'Integration was successfully updated.'
      else
        render :edit
      end
    else
      render_404
    end
  end

  def destroy
    if current_user.admin?
      @slack_integration.destroy
      redirect_to uuids_url, notice: 'Integration was successfully destroyed.'
    else
      render_404
    end
  end

  private
    def set_integration
      @slack_integration = SlackIntegration.find(params[:id])
    end

    def slack_integration_params
      params.require(:slack_integration).permit(:slack_integration, :hook_url)
    end

    def render_404
      respond_to do |format|
        format.html { render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found }
        format.xml  { head :not_found }
        format.any  { head :not_found }
      end
    end

end

app/controllers/slack_posts_controller.rb
class SlackPostsController < ApplicationController
	skip_before_filter  :verify_authenticity_token

	def index
	end

	def show
		@slack_post = SlackPost.find(params[:id])
	end

	def new
	end

	def create_entry

		@slack_post = SlackPost.new(slack_post_params)

		if @slack_post.save
			render status: 200, json: @slack_post
		else
			render :new, status: 500
		end

    post_to_integrations('@%2$s just entered %1$s' % [@slack_post.location, @slack_post.name]).html_safe
	end

	def create_exit

		@slack_post = SlackPost.new(slack_post_params)

		if @slack_post.save
			render status: 200, json: @slack_post
		else
			render :new, status: 500
		end

    post_to_integrations('@%2$s just left %1$s' % [@slack_post.location, @slack_post.name]).html_safe
	end




	private
		def slack_post_params
			params.require(:slack_post).permit(:name, :location)
		end

    def post_to_integrations(message)
      SlackIntegration.all.each { |integration|
        response = HTTParty.post(
          integration.hook_url,
          body:{text:message, link_names:1}.to_json)
      }
    end
end

app/controllers/uuids_controller.rb
class UuidsController < ApplicationController
  before_action :set_uuid, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:show, :index]

  # GET /uuids
  # GET /uuids.json
  def index
    @uuids = Uuid.all
    respond_to do |format|
      format.html { render :index }
      format.json { render json: {payload: @uuids} }
    end
  end

  # GET /uuids/1
  # GET /uuids/1.json
  def show
  end

  # GET /uuids/new
  def new
    if current_user.admin?
      @uuid = Uuid.new
    else
      render_404
    end
  end

  # GET /uuids/1/edit
  def edit
  end

  # POST /uuids
  # POST /uuids.json
  def create
    if current_user.admin?

      @uuid = Uuid.new(uuid_params)

      respond_to do |format|
        if @uuid.save
          format.html { redirect_to @uuid, notice: 'Uuid was successfully created.' }
          format.json { render :show, status: :created, location: @uuid }
        else
          format.html { render :new }
          format.json { render json: @uuid.errors, status: :unprocessable_entity }
        end
      end
    else 
      render_404
    end

  end

  # PATCH/PUT /uuids/1
  # PATCH/PUT /uuids/1.json
  def update
    if current_user.admin?
    respond_to do |format|
        if @uuid.update(uuid_params)
          format.html { redirect_to @uuid, notice: 'Uuid was successfully updated.' }
          format.json { render :show, status: :ok, location: @uuid }
        else
          format.html { render :edit }
          format.json { render json: @uuid.errors, status: :unprocessable_entity }
        end
      end
    else
      render_404
    end
  end

  # DELETE /uuids/1
  # DELETE /uuids/1.json
  def destroy
    if current_user.admin?
      @uuid.destroy
      respond_to do |format|
        format.html { redirect_to uuids_url, notice: 'Uuid was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      render_404
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_uuid
      @uuid = Uuid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def uuid_params
      params.require(:uuid).permit(:uuid, :location)
    end

    def render_404
      respond_to do |format|
        format.html { render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found }
        format.xml  { head :not_found }
        format.any  { head :not_found }
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asclear_helper.rb
module AsclearHelper
end

app/helpers/slack_integrations_helper.rb
module SlackIntegrationsHelper
end

app/helpers/slack_posts_helper.rb
module SlackPostsHelper
end

app/helpers/uuids_helper.rb
module UuidsHelper
end

app/views/admin/index.html.erb
<p id="notice"><%= notice %></p>

<ul>
  <li><a href="/admin/uuids">Manage UUIDs</a></li>
  <li><a href="/admin/slack_integrations">Manage Slack Integration</a></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BeaconApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>

<% if user_signed_in? %>
   <%= link_to('logout', destroy_user_session_path, :method => :delete) %>
<% else %>
  <%= link_to('login', new_user_session_path) %>
<% end %>

</html>

app/views/slack_integrations/_form.html.erb
<%= form_for(@slack_integration) do |f| %>
  <% if @slack_integration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slack_integration.errors.count, "error") %> prohibited this integration from being saved:</h2>

      <ul>
      <% @slack_integration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hook_url %><br>
    <%= f.text_field :hook_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/slack_integrations/edit.html.erb
<h1>Editing Integration</h1>

<%= render 'form' %>

<%= link_to 'Show', @slack_integration %> |
<%= link_to 'Back', slack_integrations_path %>

app/views/slack_integrations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Integrations</h1>

<table>
  <thead>
    <tr>
      <th>Hook URL</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @slack_integrations.each do |integration| %>
      <tr>
        <td><%= integration.hook_url %></td>
        <td><%= link_to 'Show', integration %></td>
        <td><%= link_to 'Edit', edit_slack_integration_path(integration) %></td>
        <td><%= link_to 'Destroy', integration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Integration', new_slack_integration_path %>
<%= link_to 'Back', controller: :admin, action: :index %>

app/views/slack_integrations/new.html.erb
<h1>New Integration</h1>

<%= render 'form' %>

<%= link_to 'Back', slack_integrations_path %>

app/views/slack_integrations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Integration:</strong>
  <%= @slack_integration.hook_url %>
</p>

<%= link_to 'Edit', edit_slack_integration_path(@slack_integration) %> |
<%= link_to 'Back', slack_integrations_path %>

app/views/slack_posts/index.html.erb
<h2>Why are you looking at the index?</h2>

app/views/slack_posts/new.html.erb
<%= form_for :slack_post, url: slack_posts_path do |f| %>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name%>
	</p>

	<p>
		<%= f.label :location %><br>
		<%= f.text_area :location %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/slack_posts/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @slack_post.name %>
</p>
 
<p>
  <strong>Location:</strong>
  <%= @slack_post.location %>
</p>

<p>
  <strong>Time:</strong>
  <%= @slack_post.created_at %>
</p>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/uuids/_form.html.erb
<%= form_for(@uuid) do |f| %>
  <% if @uuid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@uuid.errors.count, "error") %> prohibited this uuid from being saved:</h2>

      <ul>
      <% @uuid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uuid %><br>
    <%= f.text_area :uuid %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_area :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/uuids/edit.html.erb
<h1>Editing Uuid</h1>

<%= render 'form' %>

<%= link_to 'Show', @uuid %> |
<%= link_to 'Back', uuids_path %>

app/views/uuids/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Uuids</h1>

<table>
  <thead>
    <tr>
      <th>Uuid</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @uuids.each do |uuid| %>
      <tr>
        <td><%= uuid.uuid %></td>
        <td><%= uuid.location %></td>
        <td><%= link_to 'Show', uuid %></td>
        <td><%= link_to 'Edit', edit_uuid_path(uuid) %></td>
        <td><%= link_to 'Destroy', uuid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Uuid', new_uuid_path %>
<%= link_to 'Back', controller: :admin, action: :index %>

app/views/uuids/new.html.erb
<h1>New Uuid</h1>

<%= render 'form' %>

<%= link_to 'Back', uuids_path %>

app/views/uuids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uuid:</strong>
  <%= @uuid.uuid %>
</p>

<p>
  <strong>Location:</strong>
  <%= @uuid.location %>
</p>

<%= link_to 'Edit', edit_uuid_path(@uuid) %> |
<%= link_to 'Back', uuids_path %>